pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven-3.9'
    }

    stages {

        stage('Build') {
            steps {
                dir('jenkins') {
                    echo 'Application is in Building Phase'
                    bat 'mvn clean install'
                }
            }
        }

        stage('Deployment') {
            steps {
                dir('jenkins') {
                    bat 'mvn clean deploy -DmuleDeploy -Pdev'
                }
            }
        }
    }
}
